runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 8
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.5
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
network:
  instance_tag: paragonapi
  name: paragon
  forwarded_ports:
    - 8080/tcp
